# Generated by Django 5.1.7 on 2025-03-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_date"]},
        ),
        migrations.AddField(
            model_name="post",
            name="login_required",
            field=models.BooleanField(default=False),
        ),
    ]
